### ISSUE TITLE
`memwatch` might be leaving heap snapshots around

### ISSUE THREAD

**Issue by brianloveswords** [lloyd/node-memwatch#15]
(I'm on node 0.8.8, original question/test code here: https://gist.github.com/3971955)

Talking to lloyd on IRC trying to figure out why RSS increases and never decreases in this bad behaving stream. Expected behavior would be a spike in memory usage, then a reduction as the writes are able to get through. With memwatch included, the expected reduction never happens. lloyd suspects that heap snapshots might not be getting cleaned up.

**Comment by lloyd** [comment]
so I audited the code and it looks like we are cleaning up heap snapshots at the time the HeapDiff object is garbage collected, but in your case, you're allocating a pile of HeapDiff objects in a tight loop.  I want to confirm the diagnosis, and then maybe I can clean up snapshots in `.end()` a little more proactively, so we don't blow rss through the roof, even in this kind of usage.

So I have a theory, and a possible fix.  More in the morn'.  Thanks for the report and testcase!

**Comment by lloyd** [comment]
should be fixed with 0.2.0 - I was indeed leaking one heap snapshot per heapdiff (!!).  This was super lame.  In addition to cleaning up, I now free sooner (in end() rather than waiting for the next gc) - so using heapdiff in a tight look should be just fine.

Integrated into your `poisoned-stream.js` test case and I think you now get the kind of results you're looking for.  I wonder if wrapping the program with a heapdiff (before you write to the stream to after it is flushed) will give you a meaningful picture of what's going on?

much <3
